-- USUÁRIO BASE
CREATE TABLE USUARIO (
    CPF_CNPJ VARCHAR2(14) NOT NULL, --CPF com traço e pontos ou CNPJ só números
    NOME VARCHAR2(50) NOT NULL,
    TELEFONE VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(50) NOT NULL, --TIPO VARCHAR2(13) NOT NULL, --Aparentemente n se usa
    TIPO VARCHAR2(13) NOT NULL,
    CONSTRAINT PK_CPF_CPNJ_USUARIO PRIMARY KEY (CPF_CNPJ),
    CONSTRAINT UNIQUE_EMAIL_USUARIO UNIQUE (EMAIL),
    CONSTRAINT CHECK_TIPO_USUARIO CHECK ((TIPO) IN ('DOADOR', 'BENEFICIARIO', 'ADMIN', 'TRANSPORTADOR')),
    CONSTRAINT CHECK_EMAIL_FORMAT CHECK (REGEXP_LIKE((EMAIL), '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,10}$'))    
);

-------------------------------------------------------------------------------

-- BLOCO BENEFÍCIARIO
-- NESSE BLOCO OBSERVAM-SE TABELAS RELACIONADAS AOS USUÁRIOS BENEFICIÁRIOS
CREATE TABLE BENEFICIARIO (
    USUARIO_BEN VARCHAR2(14) NOT NULL,
    CONSTRAINT PK_USUARIO_BENEFICIARIO PRIMARY KEY (USUARIO_BEN), 
    CONSTRAINT FK_USUARIO_BEN_TIPO FOREIGN KEY (USUARIO_BEN) REFERENCES USUARIO (CPF_CNPJ) ON DELETE CASCADE
);

CREATE TABLE REQUISICAO (
    ID NUMBER NOT NULL,
    BENEFICIARIO_ VARCHAR2(14) NOT NULL,
    STATUS VARCHAR2(10),
    DATA_CRIACAO DATE,
    TIPO  VARCHAR2(8) DEFAULT 'RETIRADA' NOT NULL, --CASO O BENEFICIARIO N SE PRONUNCIE, RETIRADA
    CONSTRAINT PK_REQUISICAO PRIMARY KEY (ID),
    CONSTRAINT FK_BEN_REQ FOREIGN KEY (BENEFICIARIO_) REFERENCES BENEFICIARIO (USUARIO_BEN),
    CONSTRAINT CHECK_STATUS_REQUISICAO_VAL CHECK((STATUS) IN ('PENDENTE', 'FINALIZADA')), -- DEFINIR STATUS
    CONSTRAINT CHECK_TIPO_REQ CHECK((TIPO) IN ('RETIRADA', 'ENTREGA')) --DEFINIR COMO TRIGGER ESCUDOS PARA N CRIAR DATA MENOR Q O MOMENTO ATUAL
);

CREATE TABLE REQ_RETIRADA (
    REQUISICAO_ NUMBER NOT NULL,
    DATA_RETIRADA DATE,
    CONSTRAINT PK_REQ_RETIRADA PRIMARY KEY (REQUISICAO_),
    CONSTRAINT FK_REQ_RETIRADA FOREIGN KEY (REQUISICAO_) REFERENCES REQUISICAO (ID)
);

CREATE TABLE AVALIACAO (
    REQUISICAO_ NUMBER NOT NULL,
    DESCRICAO VARCHAR2(256),
    EH_DENUNCIA CHAR(1) DEFAULT '0' NOT NULL,
    EH_FEEDBACK CHAR(1) DEFAULT '0' NOT NULL,
    CONSTRAINT PK_AVALICAO_REQ PRIMARY KEY (REQUISICAO_),
    CONSTRAINT FK_AVALICAO_REQ FOREIGN KEY (REQUISICAO_) REFERENCES REQUISICAO (ID) ON DELETE CASCADE,
    CONSTRAINT CHECK_DEN_AVA CHECK (EH_DENUNCIA IN ('0','1')),
    CONSTRAINT CHECK_FED_AVA CHECK (EH_FEEDBACK IN ('0','1')), 
    CONSTRAINT CHECK_DEN_DIF_FED_AVA CHECK (NOT (EH_DENUNCIA = '0' AND EH_FEEDBACK = '0')) 
);

-------------------------------------------------------------------------------

-- BLOCO DE TRANSPORTADOR
-- NESSE BLOCO PODEMOS OBSERVAR TABELAS RELACIONADAS AOS USUÁRIOS COM A FUNÇÃO DE TRANSPORTADOR
CREATE TABLE TRANSPORTADOR (
    USUARIO_TRA VARCHAR2(14) NOT NULL,
    CONSTRAINT PK_USUARIO_TRANSPORTADOR PRIMARY KEY (USUARIO_TRA), 
    CONSTRAINT FK_USUARIO_TRA FOREIGN KEY (USUARIO_TRA) REFERENCES USUARIO (CPF_CNPJ) ON DELETE CASCADE
);

CREATE TABLE REQ_ENTREGA (
    REQUISICAO_ NUMBER NOT NULL,
    DESTINO VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_REQUISICAO_ENTREGA PRIMARY KEY (REQUISICAO_),
    CONSTRAINT FK_REQ_REQ_ENTREGA FOREIGN KEY (REQUISICAO_) REFERENCES REQUISICAO (ID)
);

CREATE TABLE ENTREGA (
    CODIGO NUMBER NOT NULL,
    REQ_ENTREGA_ NUMBER NOT NULL,
    TRANSPORTADOR_ VARCHAR2(14) NOT NULL,
    VEICULO VARCHAR2(20) NOT NULL,
    STATUS VARCHAR2(10) NOT NULL,
    DATA_COLETA DATE NOT NULL,
    PREVISAO_ENTREGA DATE,
    DATA_ENTREGA DATE,
    CONSTRAINT PK_ENTREGA_CODIGO PRIMARY KEY (CODIGO),
    CONSTRAINT UN_ENTREGA_REQ UNIQUE (REQ_ENTREGA_),
    CONSTRAINT FK_ENTREGA_TRA FOREIGN KEY (TRANSPORTADOR_) REFERENCES TRANSPORTADOR (USUARIO_TRA),
    CONSTRAINT FK_REQ_ENTREGA FOREIGN KEY (REQ_ENTREGA_) REFERENCES REQ_ENTREGA (REQUISICAO_),
    CONSTRAINT CHECK_STATUS_ENTREGA_VAL CHECK((STATUS) IN ('PENDENTE', 'EM_ROTA', 'FINALIZADA')), --DEFINIR TIPOS
    CONSTRAINT CHECK_DATAS_ENTREGA CHECK (DATA_COLETA <= DATA_ENTREGA)
);

-------------------------------------------------------------------------------

-- DOADOR DA PLATAFORMA
CREATE TABLE DOADOR (
    USUARIO_DOA VARCHAR2(14) NOT NULL,
    ENDERECO VARCHAR2(50) NOT NULL,
    INTERVALO_RETIRADA VARCHAR2(20), --pode ser nulo, ex, doador n tem retirada, só entrega
    HORARIO_FUNCIONAMENTO VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_USUARIO_DOADOR PRIMARY KEY (USUARIO_DOA), 
    CONSTRAINT FK_USUARIO_DOADOR FOREIGN KEY (USUARIO_DOA) REFERENCES USUARIO (CPF_CNPJ) ON DELETE CASCADE
);

CREATE TABLE LOTE_ITEM (
    CODIGO_LOTE NUMBER NOT NULL,
    DOADOR_ VARCHAR2(14) NOT NULL,
    REQUISICAO_BEN NUMBER, --NÃO PODE SER NOT NULL, LOTE DE ITEM VEM ANTES DE REQ
    PRECO NUMBER NOT NULL,
    CATEGORIA VARCHAR2(15) NOT NULL,
    QUANTIDADE_ITENS NUMBER,
    VALIDADE DATE NOT NULL,
    NOME VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_LOTE_ITEM PRIMARY KEY (DOADOR_, CODIGO_LOTE),
    CONSTRAINT FK_DOA_LOTE_ITEM FOREIGN KEY (DOADOR_) REFERENCES DOADOR (USUARIO_DOA), --ENTY FRACA DE DOADOR
    CONSTRAINT FK_REQ_BEN FOREIGN KEY (REQUISICAO_BEN) REFERENCES REQUISICAO (ID) --MANTÉM? --DEFINIR COMO TRIGGER ESCUDOS PARA N CRIAR DATA DE VALIDADE MENOR Q MOMENTO ATUAL
);

-------------------------------------------------------------------------------

-- ADMIN PARA MODERAÇÃO DE DENÚNCIAS
CREATE TABLE ADMIN (
    USUARIO_ADM VARCHAR2(14) NOT NULL,
    CONSTRAINT PK_USUARIO_ADMIN PRIMARY KEY (USUARIO_ADM), 
    CONSTRAINT FK_USUARIO_ADM FOREIGN KEY (USUARIO_ADM) REFERENCES USUARIO (CPF_CNPJ) ON DELETE CASCADE
);

CREATE TABLE DENUNCIA (
    AVALIACAO_REQ NUMBER NOT NULL,
    CATEGORIA VARCHAR2(25) NOT NULL,
    CONSTRAINT PK_DENUNCIA_REQ PRIMARY KEY (AVALIACAO_REQ),
    CONSTRAINT FK_DENUNCIA_REQ FOREIGN KEY (AVALIACAO_REQ) REFERENCES AVALIACAO (REQUISICAO_) ON DELETE CASCADE,
    CONSTRAINT CHECK_CAT_DENUN CHECK(CATEGORIA IN (
        'PRODUTO_VENCIDO', 
        'DIVERGENCIA', 
        'FALHA_LOGISTICA', 
        'EXTRAVIO', 
        'MAU_ACONDICIONAMENTO', 
        'FRAUDE', 
        'COMPORTAMENTO', 
        'OUTROS'
    ))
);

CREATE TABLE FEEDBACK (
    AVALIACAO_REQ NUMBER NOT NULL,
    NOTA NUMBER NOT NULL,
    CONSTRAINT PK_FEEDBACK_REQ PRIMARY KEY (AVALIACAO_REQ),
    CONSTRAINT FK_FEEDBACK_REQ FOREIGN KEY (AVALIACAO_REQ) REFERENCES AVALIACAO (REQUISICAO_) ON DELETE CASCADE,
    CONSTRAINT CHECK_NOTA_VAL CHECK((NOTA) > 0 AND (NOTA) <= 5)
);

CREATE TABLE MODERACAO (
    ADM VARCHAR2(14) NOT NULL,
    DOADOR VARCHAR2(14) NOT NULL,
    CONSTRAINT PK_MODERACAO PRIMARY KEY (ADM, DOADOR),
    CONSTRAINT FK_USUARIO_ADM_MODERA FOREIGN KEY (ADM) REFERENCES ADMIN (USUARIO_ADM),
    CONSTRAINT FK_USUARIO_DOADOR_MODERA FOREIGN KEY (DOADOR) REFERENCES DOADOR (USUARIO_DOA)
);

-------------------------------------------------------------------------------
--DEFINIÇÃO DOS TRIGGERS PARA DATAS INVÁLIDAS

CREATE OR REPLACE TRIGGER TRG_VALIDA_REQUISICAO
BEFORE INSERT OR UPDATE ON REQUISICAO
FOR EACH ROW
BEGIN
    IF :NEW.DATA_CRIACAO < SYSDATE THEN
        RAISE_APPLICATION_ERROR(-20001, 'A data de criação da requisição deve ser superior ou igual a data atual.');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_VALIDA_LOTE
BEFORE INSERT OR UPDATE ON LOTE_ITEM
FOR EACH ROW
BEGIN
    IF :NEW.VALIDADE <= SYSDATE THEN
        RAISE_APPLICATION_ERROR(-20002, 'A validade do item deve ser superior a data atual.');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_VALIDA_REQ_RETIRADA
BEFORE INSERT OR UPDATE ON REQ_RETIRADA
FOR EACH ROW
BEGIN
    IF :NEW.DATA_RETIRADA < SYSDATE THEN
        RAISE_APPLICATION_ERROR(-20003, 'A data de retirada do item deve ser superior ou igual a data atual.');
    END IF;
END;
/

EXIT;