-- USUÁRIO BASE
CREATE TABLE USUARIO (
    CPF_CNPJ VARCHAR2(14) NOT NULL, --CPF com traço e pontos ou CNPJ só números
    NOME VARCHAR2(50) NOT NULL,
    TELEFONE VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(50) NOT NULL,
    --TIPO VARCHAR2(13) NOT NULL, --Aparentemente n se usa

    CONSTRAINT PK_CPF_CPNJ_USUARIO PRIMARY KEY (CPF_CNPJ),
    CONSTRAINT UNIQUE_EMAIL_USUARIO UNIQUE (EMAIL),
    CONSTRAINT CHECK_EMAIL_FORMAT CHECK (REGEXP_LIKE(EMAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,10}$'))    
);

-------------------------------------------------------------------------------

-- BLOCO DE TRANSPORTADOR
-- NESSE BLOCO PODEMOS OBSERVAR TABELAS RELACIONADAS AOS USUÁRIOS COM A FUNÇÃO DE TRANSPORTADOR
CREATE TABLE TRANSPORTADOR (
    USUARIO_TRA VARCHAR2(14) NOT NULL,

    CONSTRAINT PK_USUARIO_TRANSPORTADOR PRIMARY KEY (USUARIO_TRA), 
    CONSTRAINT FK_USUARIO_TRANSPORTADOR FOREIGN KEY (USUARIO_TRA) REFERENCES USUARIO (CPF_CNPJ)
);

CREATE TABLE REQ_ENTREGA (
    REQUISICAO_ NUMBER NOT NULL,
    DESTINO VARCHAR2(50) NOT NULL,

    CONSTRAINT PK_REQUISICAO_ENTREGA PRIMARY KEY (REQUISICAO_),
    --ADICIONAR AS CONSTRAINTS NO FIM PARA CADA VALOR (REQUISICAO)
    --FIZ DESSA FORMA PARA O DB FICAR SEMÂNTICAMENTE MAIS FÁCIL DE ENTENDER
);

CREATE TABLE ENTREGA (
    CODIGO NUMBER NOT NULL,
    REQ_ENTREGA_ NUMBER NOT NULL,
    TRANSPORTADOR_ VARCHAR2(50) NOT NULL,
    VEICULO VARCHAR2(20) NOT NULL,
    STATUS VARCHAR2(10) NOT NULL,
    DATA_COLETA DATE NOT NULL,
    PREVISAO_ENTREGA DATE,
    DATA_ENTREGA DATE,

    CONSTRAINT PK_ENTREGA_CODIGO PRIMARY KEY (CODIGO),
    CONSTRAINT FK_REQ_ENTREGA FOREIGN KEY (REQ_ENTREGA_) REFERENCES REG_ENTREGA (REQUISICAO),
    CONSTRAINT CHECK_STATUS_ENTREGA CHECK(STATUS IN ''), --DEFINIR TIPOS
);
-- AS CHAVES FALTANTES QUE SERÃO INSERIDAS NO FINAL SÃO: 'REQUISICAO (ID)'

-------------------------------------------------------------------------------

-- BLOCO BENEFÍCIARIO
-- NESSE BLOCO OBSERVAM-SE TABELAS RELACIONADAS AOS USUÁRIOS BENEFICIÁRIOS
CREATE TABLE BENEFICIARIO (
    USUARIO_BEN VARCHAR2(14) NOT NULL,

    CONSTRAINT PK_USUARIO_BENEFICIARIO PRIMARY KEY (USUARIO_BEN), 
    CONSTRAINT FK_USUARIO_BENEFICIARIO FOREIGN KEY (USUARIO_BEN) REFERENCES USUARIO (CPF_CNPJ)
);

-- TABELAS FALTANDO:
-- REQUISICAO
-- REQ_RETIRADA
-- AVALIACAO

-------------------------------------------------------------------------------

-- ADMIN PARA MODERAÇÃO DE DENÚNCIAS
CREATE TABLE ADMIN (
    USUARIO_ADM VARCHAR2(14) NOT NULL,

    CONSTRAINT PK_USUARIO_ADMIN PRIMARY KEY (USUARIO_ADM), 
    CONSTRAINT FK_USUARIO_ADMIN FOREIGN KEY (USUARIO_ADM) REFERENCES USUARIO (CPF_CNPJ)
);

-- TABELAS FALTANDO:
-- DENUNCIA
-- FEEDBACK
-- MODERACAO

-------------------------------------------------------------------------------

-- DOADOR DA PLATAFORMA
CREATE TABLE DOADOR (
    USUARIO_DOA VARCHAR2(14) NOT NULL,
    ENDERECO VARCHAR2(50) NOT NULL,
    INTERVALO_RETIRADA VARCHAR2(20), --pode ser nulo, ex, doador n tem retirada, só entrega
    HORARIO_FUNCIONAMENTO VARCHAR2(20) NOT NULL,

    CONSTRAINT PK_USUARIO_DOADOR PRIMARY KEY (USUARIO_DOA), 
    CONSTRAINT FK_USUARIO_DOADOR FOREIGN KEY (USUARIO_DOA) REFERENCES USUARIO (CPF_CNPJ)
    --CONSTRAINT --TALVEZ VALHA A PENA FAZER MAIS VERIFICAÇÕES AQ
);

-- TABELAS FALTANDO:
-- LOTE DE ITEM

-------------------------------------------------------------------------------

-- DEFINIÇÕES DAS FKs NÃO DEFINIDAS ANTERIORMENTE

ALTER TABLE <TABLE> 
    ADD CONSTRAINT <FUNCAO> FOREIGN KEY (<KEY>) REFERENCES <REF_TABLE> (<REF_KEY>);